apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc-demo-by-hl
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31080
  selector:
    app: nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx-demo-by-hl
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-demo-by-hl
        image: hleon256/nginx:latest
        ports:
        - containerPort: 80

